apiVersion: apps/v1
kind: Deployment
metadata:
  name: querry-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querry
  template:
    metadata:
      labels:
        app: querry
    spec:
      containers:
        - name: querry
          image: chaiben/querry
---
apiVersion: v1
kind: Service
metadata:
  name: querry-srv
spec:
  type: ClusterIP # default (this line is optional)
  selector:
    app: querry
  ports:
    - name: querry
      protocol: TCP
      port: 4002
      targetPort: 4002
